apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nginx-ingress-controller-deployment.yaml
  - nginx-ingress-service.yaml
  - microrts-api-ingress.yaml

namespace: ingress