apiVersion: v1
kind: Service
metadata:
  name: shippingservice-svc
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 9233
      targetPort: 9233
  type: LoadBalancer
