name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  CLUSTER_NAME: hipstershop-cluster
  ZONE: us-central1-c
  PROJECT_ID: microrts-sample

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool
        run: |
          gcloud auth configure-docker

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

      - name: Get GKE Auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Build and Deploy cartservice
        run: |
          # cart service
          ./kustomize build ./cart-service | kubectl apply -f -
          until kubectl get deployment cartservice; do sleep 1; done
          kubectl rollout status deployment/cartservice
          kubectl get services -o wide

      - name: Build and Deploy inventoryservice
        run: |
          # inventory service
          ./kustomize build ./inventory-service | kubectl apply -f -
          until kubectl get deployment inventoryservice; do sleep 1; done
          kubectl rollout status deployment/inventoryservice
          kubectl get services -o wide

      - name: Build and Deploy orderservice
        run: |
          # order service
          ./kustomize build ./order-service | kubectl apply -f -
          until kubectl get deployment orderservice; do sleep 1; done
          kubectl rollout status deployment/orderservice
          kubectl get services -o wide

      - name: Build and Deploy paymentservice
        run: |
          # payment service
          ./kustomize build ./payment-service | kubectl apply -f -
          until kubectl get deployment paymentservice; do sleep 1; done
          kubectl rollout status deployment/paymentservice
          kubectl get services -o wide

      - name: Build and Deploy productservice
        run: |
          # product service
          ./kustomize build ./product-service | kubectl apply -f -
          until kubectl get deployment productservice; do sleep 1; done
          kubectl rollout status deployment/productservice
          kubectl get services -o wide

      - name: Build and Deploy shippingservice
        run: |
          # shipping service
          ./kustomize build ./shipping-service | kubectl apply -f -
          until kubectl get deployment shippingservice; do sleep 1; done
          kubectl rollout status deployment/shippingservice
          kubectl get services -o wide

      - name: Build and Deploy userservice
        run: |
          # user service
          ./kustomize build ./user-service | kubectl apply -f -
          until kubectl get deployment userservice; do sleep 1; done
          kubectl rollout status deployment/userservice
          kubectl get services -o wide
