name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  CLUSTER_NAME: hipstershop-cluster
  ZONE: us-central1-c
  PROJECT_ID: microrts-sample
  MICRORTS_NS: microrts
  HIPSTERSHOP_NS: hipstershop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool
        run: |
          gcloud auth configure-docker

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

      - name: Get GKE Auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Build and Deploy the microrts api
        run: |
          ./kustomize build ./microrts-api | kubectl apply -f -

      - name: Build and Deploy all the hisptershop services
        run: |
          ./kustomize build ./hipstershop | kubectl apply -f -

      - name: Check deployment
        run: |
          kubectl rollout status deployment/micrortsapi -n $MICRORTS_NS
          kubectl rollout status deployment/cartservice -n $HIPSTERSHOP_NS
          kubectl rollout status deployment/inventoryservice -n $HIPSTERSHOP_NS
          kubectl rollout status deployment/paymentservice -n $HIPSTERSHOP_NS
          kubectl rollout status deployment/productservice -n $HIPSTERSHOP_NS
          kubectl rollout status deployment/orderservice -n $HIPSTERSHOP_NS
          kubectl rollout status deployment/shippingservice -n $HIPSTERSHOP_NS
          kubectl rollout status deployment/userservice -n $HIPSTERSHOP_NS
          kubectl get services -o wide