name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  CLUSTER_NAME: hipstershop-cluster
  ZONE: us-central1-a
  PROJECT_ID: microrts-sample

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool
        run: |
          gcloud auth configure-docker
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Build and Deploy Microservices
        run: |
          # Replace the following with appropriate Kustomize commands for each microservice
          ./kustomize build ./cart-service | kubectl apply -f -
          kubectl rollout status deployment/cartservice
          kubectl get services -o wide
